### ISSUE TITLE
Fix lint issues discovered by golangci-lint

### ISSUE THREAD

**Issue by prabhu43** [litmuschaos/chaos-operator#291] opened 2020-10-22 19:02 UTC
Refactor: Related to issue #276

To use golangci-lint in CI, fix the issues discovered by golangci-lint

**Comment by ispeakc0de** [comment] 2024-03-14 05:07
It is duplicate of https://github.com/litmuschaos/chaos-operator/issues/276 issue

**Closed by ispeakc0de** 2024-03-14 05:07 UTC
